# Generated by Django 5.0.3 on 2024-03-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0004_alter_appform_questions'),
        ('users', '0003_remove_profile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_forms',
            field=models.ManyToManyField(blank=True, related_name='my_forms', to='appforms.appform'),
        ),
    ]
