# Generated by Django 5.0.3 on 2024-03-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
