# Generated by Django 5.0.3 on 2024-03-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
