# Generated by Django 5.0.3 on 2024-03-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppForm',
        ),
    ]
