# Generated by Django 5.0.3 on 2024-03-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0003_initial'),
        ('questions', '0008_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appform',
            name='questions',
            field=models.ManyToManyField(blank=True, to='questions.questions'),
        ),
    ]
