# Generated by Django 5.0.3 on 2024-03-17 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0004_alter_appform_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appform',
            name='filled_by',
            field=models.ManyToManyField(blank=True, related_name='filled_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
