# Generated by Django 5.0.3 on 2024-03-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0005_appform_filled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appform',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
