# Generated by Django 5.0.3 on 2024-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0007_appform_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appform',
            name='code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
