# Generated by Django 5.0.3 on 2024-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0008_alter_appform_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appform',
            name='ask_code',
            field=models.BooleanField(default=False),
        ),
    ]
