# Generated by Django 5.0.3 on 2024-03-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0009_appform_ask_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appform',
            name='form_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
