# Generated by Django 5.0.3 on 2024-03-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0010_appform_form_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appform',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
