# Generated by Django 5.0.3 on 2024-03-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0011_appform_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appform',
            name='changed_time',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='appform',
            name='is_changed',
            field=models.BooleanField(default=False),
        ),
    ]
