# Generated by Django 5.0.3 on 2024-03-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0012_appform_changed_time_appform_is_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appform',
            name='changed_time',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
