# Generated by Django 5.0.3 on 2024-03-08 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_openended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, max_length=10000)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
            ],
        ),
    ]
