# Generated by Django 5.0.3 on 2024-03-08 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='author',
        ),
        migrations.AddField(
            model_name='questions',
            name='author',
            field=models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
