# Generated by Django 5.0.3 on 2024-03-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0002_delete_appform'),
        ('questions', '0004_remove_questions_author_questions_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optional',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='author',
        ),
        migrations.DeleteModel(
            name='OpenEnded',
        ),
        migrations.DeleteModel(
            name='Optional',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
