# Generated by Django 5.0.3 on 2024-03-08 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0005_remove_optional_question_remove_questions_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=18)),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('Optional', 'Optional'), ('MultiChoices', 'Multi Choices'), ('OpenEnded', 'Open Ended'), ('Rank', 'Rank')], default='OpenEnded', max_length=12)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Optional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(blank=True, max_length=10000)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
            ],
        ),
        migrations.CreateModel(
            name='OpenEnded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
            ],
        ),
    ]
