# Generated by Django 5.0.3 on 2024-03-09 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0004_alter_appform_questions'),
        ('questions', '0008_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='belongs_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='appforms.appform'),
        ),
    ]
