# Generated by Django 5.0.3 on 2024-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_questions_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='options',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
