# Generated by Django 5.0.3 on 2024-03-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_questions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('OpenEnded', 'Open Ended'), ('Optional', 'Optional'), ('MultiChoices', 'Multi Choices'), ('Rank', 'Rank')], default='OpenEnded', max_length=12),
        ),
    ]
