# Generated by Django 5.0.3 on 2024-03-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_alter_questions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('Optional', 'Optional'), ('MultiChoices', 'Multi Choices'), ('OpenEnded', 'Open Ended'), ('Rank', 'Rank')], default='OpenEnded', max_length=12),
        ),
    ]
