# Generated by Django 5.0.3 on 2024-03-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_questions_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoice',
            name='multichoices',
        ),
        migrations.RemoveField(
            model_name='optional',
            name='choices',
        ),
    ]
