# Generated by Django 5.0.3 on 2024-03-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_remove_multichoice_multichoices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
