# Generated by Django 5.0.3 on 2024-03-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_alter_answer_answered_by'),
        ('questions', '0015_questions_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openended',
            name='question',
        ),
        migrations.RemoveField(
            model_name='optional',
            name='question',
        ),
        migrations.RemoveField(
            model_name='rank',
            name='question',
        ),
        migrations.AddField(
            model_name='questions',
            name='answers',
            field=models.ManyToManyField(blank=True, to='answers.answer'),
        ),
        migrations.DeleteModel(
            name='MultiChoice',
        ),
        migrations.DeleteModel(
            name='OpenEnded',
        ),
        migrations.DeleteModel(
            name='Optional',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
